site_name: Docs
pages:
- Projects: index.md
- XML Editor:
    - Intro: xml_editor/index.md 
    - Installation: xml_editor/install.md
    - Usage: xml_editor/config.md
    - Development: xml_editor/dev.md
- Questionnaire:
    - Intro: fsq/index.md
    - Installation: fsq/install.md
    - Configuration: fsq/config.md
    - Development: fsq/dev.md
- Renderer:
    - Overview: fs_renderer/index.md
    - Installation: fs_renderer/install.md
    - Configuration: fs_renderer/config.md
    - Development: fs_renderer/dev.md
- XML Objectifier:
    - Intro: xml_objectifier/index.md
    - Installation: xml_objectifier/install.md
    - Usage: xml_objectifier/usage.md
- Tips:
    - Shortcuts: tips/shortcuts.md
theme: slate

